### ISSUE TITLE
How to enable colors in typescript

### ISSUE THREAD

**Issue by it6** [ananthakumaran/typescript.el#32]
Hi, in js2-mode I see defface variables
```
(defface js2-function-call
  '((t :inherit default))
  "Face used to highlight function name in calls."
  :group 'js2-mode)
``` 
and in my themes file I added
```(js2-function-call (:foreground ,green))```
to make the function call green.

Is there any similar way to add my theme specific colors for typescript. Thanks.

**Comment by josteink** [comment]
Currently we just re-use the default Emacs faces for pretty much everything. You can see it here:

https://github.com/ananthakumaran/typescript.el/blob/master/typescript-mode.el#L306-L317

I'm sure you'll find similar definitions if you scroll through the code.

So in order to get the functionality you want, `typescript.el` will need some patches which:

1. creates mode-specific `defface`-statements with appropriate defaults.
2. replaces hard-coded usage of Emacs default-faces with the face-types created in 1.

Nobody is actively working towards this, but if you feel like putting in some work, PRs are very much welcome.

**Comment by 1-9** [comment]
I can help with this effort but not sure where to start can you guide me @josteink.

**Comment by josteink** [comment]
Basically you need to do a few things:

* Identify all the faces currently used by typescript-mode (i.e. `font-lock-function-name-face`). See my previous comment for an example of such usage.
* Create corresponding mode-specific face using `defface` (i.e. `typescript-function-name-face`), with appropriate defaults matching the original Emacs-faces. I tried to locate some examples for this, and it seems `js2-mode` does exactly this. Take a peek at [its code](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L985-L1118) to see how it works.
* Rewire all the existing code which makes use of pre-defined Emacs font-lock faces to use your newly defined mode-specific custom faces.

If you're new to this, it'll probably take a bit of time and effort, but all in all it shouldn't at any point involve anything fundamentally complex.

**Comment by 1-9** [comment]
Instead of reinventing the wheel, is there any way we can port the official syntax highlights from Typescript to emacs.

https://github.com/Microsoft/TypeScript-TmLanguage

**Comment by josteink** [comment]
That would be awesome.  But given that we mostly have something which works right now though, I'm not going to put in the effort myself though.

If anyone gets it done though, I would be all for it.

**Comment by josteink** [comment]
This comment here is relevant to this issue: https://github.com/ananthakumaran/typescript.el/pull/78#issuecomment-409479553

Basically there seems there is a generalized solution to this problem which can be applied to all major-modes, instead of having every major-mode reimplement the same font-lock inheritance layering.

As such, I'm inclined to close this issue as "won't fix" unless anyone can convince me otherwise.

**Comment by josteink** [comment]
Based on closing #78, I've decided to close this issue too as "won't fix".

Disagreement is OK, but then I'll need some really convincing arguments :)
