### ISSUE TITLE
typescript-insert-and-indent is misbehaving in 20170526.239

### ISSUE THREAD

**Issue by notnarb** [ananthakumaran/typescript.el#37]
Under certain indentation scenarios such as within a class method, inserting a key bound to `(typescript-insert-and-indent KEY)` seems to move the cursor back 7 characters.

This problem does not appear in 0.2 available in melpa-stable

---
My steps to reproduce:
Prerequisites: emacs 25.1.1 from Fedora 25 repos `(GNU Emacs 25.1.1 (x86_64-redhat-linux-gnu) of 2016-12-15)`
1. Create empty .emacs.d/init.el containing
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
```
2. `M-x package-refresh-contents` `M-x package-install typescript-mode` (should install version 20170526.239 as of right now)
3. Open new ts file containing a class with instance methods
4. Attempt to type something such as "const a = new Promise(" within an instance method
5. Observe that cursor has moved ~7 characters backwards

Quick gif of me reproducing steps 3 through 5:
![2017-05-30_01-37-03](https://cloud.githubusercontent.com/assets/1731591/26575190/075a522c-44d9-11e7-97cb-7f6c72b3a035.gif)

---
My workaround for now is to just use typescript-mode from melpa-stable (0.2) which behaves as expected:

![2017-05-30_02-03-38](https://cloud.githubusercontent.com/assets/1731591/26576025/4b1479a4-44dc-11e7-9a97-eb2378b167f4.gif)

**Comment by josteink** [comment]
Thanks for the very detailed bug-report! I can reproduce this one. 

From what I can tell `indent-according-to-mode` calls back into `typescript-indent-line` (which was fixed for another error 26.05.2017) and this seems to introduce the error.

In your example our new "unicode-aware" `typescript--current-column` function returns `23` where regular `current-column` returns `30` (which is also reported by `column-number-mode`) This causes the cursor to be positioned incorrectly. This is obviously wrong.

Looking at it in depth, it seems this was caused by the first char of the line actually being a `tab`, which column-wise would represent `8` spaces.

A temporary workaround could be not to use tabs, but prefer spaces, but I can see how that doesn't work out for everyone.

I'm not sure what a good solution for everyone would be here, but I'll try to take a deeper look at it.

**Comment by josteink** [comment]
**Update:** basically it seems like the `column` and `char` concept in Emacs is not really compatible, and should not ever be mixed when doing accounting:

* a single Chinese/Wide unicode character counts as several "columns", but as 1 character.
* a tab counts as 1 character, but also as several columns.

As long as `typescript-indent-line` mixes these, we will get errors, and I think the best approach is to rewrite it to use columns exclusively.

This means we'll have to replace `forward-char` with `move-to-column` for repositioning.

**Comment by josteink** [comment]
Added another test-case. With this patch in, indentation works for both tabs and wide chars.

Let me know if it works for you as well.

**Comment by notnarb** [comment]
Thank you for the extremely fast turnaround!
As of 20170530.953, this issue appears to be fixed for me.

And thank you for the in-depth explanation!  One day I hope to better be able to contribute to elisp projects so I find this stuff very interesting

**Comment by josteink** [comment]
Thanks for reporting back! Glad to hear your issues are solved.

As for detailed explanation... Consider it thinking out loudly. Sometimes I can't figure out how to fix things, but I have made concrete findings. By reporting these it may help other Emacs'ers spot the error instead. ;)
