### ISSUE TITLE
Highlighting of typecontraints, known variables, methods/properties

### ISSUE THREAD

**Issue by bklaase** [ananthakumaran/typescript.el#52]
Maybe I am doing something wrong, but it seems that there are quite a few elements still unthemed:
![image](https://user-images.githubusercontent.com/8513117/29872751-321ad684-8d91-11e7-8848-8adc90646951.png)
keywords, declarations of both functions and variables, definitions of types/interfaces all works pretty well. But the actual usage of previously declared objects / function calls,seems to result in default faces. 

Another one:
![image](https://user-images.githubusercontent.com/8513117/29872923-d69979a4-8d91-11e7-8826-e785702891fd.png)
`new Date(..` looks great, but `SimulatedTransaction` is a type too. Shouldn't it receive the same highlighting? That is to say: `font-lock-type-face`

I'm relatively new to Emacs (1.5 months), but more then willing to put in work to help achieve this (, or to receive scorn for assuming this is easily accomplished).

**Comment by lddubeau** [comment]
I don't think `typescript-mode` can solve this *in general*. If you do `import { x } from "foo"`, is `x` a type or a variable? `typescript-mode` cannot know because it does not have the machinery necessary to load `"foo"` and check.

On the other hand, it should be *possible* to have [`tide`](https://github.com/ananthakumaran/tide) (which can figure out what `x` is in my example above) augment the fontification provided by `typescript-mode`. Looking quickly at its code I do not see any such case of augmentation now, but in theory, it should be possible.

**Comment by bklaase** [comment]
hmm yes, I can see that makes sense for tokens that need to be inferred. How about though:
- the type assertions in function declaration? 
- something ending with parentheses is a function?

**Comment by josteink** [comment]
I'm sure there are room for improvements. Feel free to issue patches for it.

**Comment by bklaase** [comment]
Yes, that's definitely fair. I would love to be able to give something back, since working with this in concert with `tide` is a joy.
Can you point me maybe a little in the direction of where to look?
