### ISSUE TITLE
Mode is not considered to derive from prog-mode

### ISSUE THREAD

**Issue by blaenk** [ananthakumaran/typescript.el#75]
I was trying to use `helm-imenu-in-all-buffers` which is a helm command which combines the imenu output of all buffers with the same mode, but part of the filtering process is to ensure that the buffer derives from `prog-mode`, so the resulting list is empty because `typescript-mode` is not considered to derive from `prog-mode`.

I noticed that this mode has an interesting way of defining the parent mode by aliasing either `prog-mode` or `fundamental-mode` to `typescript-parent-mode`:

https://github.com/ananthakumaran/typescript.el/blob/7a5c74d88e3c5513cc4431a837003736f905a75e/typescript-mode.el#L2588-L2593

I would have hoped that this would still mean that `(derived-mode-p 'prog-mode)` would be true, but it doesn't. Instead, `(derived-mode-p 'typescript-parent-mode)` yields true, although that's of little use.

Is there any chance we can explicitly set it to `prog-mode`, even if by a user-defined opt-in option? I think it would be desirable because for better or worse, a lot of packages and configuration seem to check that a buffer's mode is `prog-mode` derived, which can lead to functionality breaking in subtle ways.

Reference: emacs-helm/helm#2052

**Comment by lddubeau** [comment]
Ouch... `define-derived-mode` is a macro which stores its `parent` parameter as a quoted value, which is why we end up with the current behavior.

For the life of me, I cannot see why we have that indirection through `typescript-parent-mode`. If I run `git blame` on the code, I see that setup dates from the initial commit and so was probably inherited from `js-mode`. If I look at the current `js-mode` bundled with my Emacs, however, there's no such equivalent indirection there. Searching through Emacs's commits, I see `prog-mode` was added to Emacs 24.1 (which dates from 2012 according to Wikipedia). So I guess if `typescript-mode` is to be used with versions of Emacs *older than that*, it needs to be able to fall back on `fundamental-mode`, but do we need to support versions that old?

I'd answer that question with a "no" (the oldest version in our test matrix for Travis is 24.3) and fix the issue by making `typescript-mode` inherit directly from `prog-mode` and drop the whole `typescript-parent-mode` indirection.

@ananthakumaran @josteink Am I missing something?

**Comment by josteink** [comment]
No. That’s exactly it.

If every version of Emacs we support also does supports prog-mode, we can remove this indirection without any further ceremony.
