### ISSUE TITLE
Handling for `undefined` type

### ISSUE THREAD

**Issue by jack-williams** [ananthakumaran/typescript.el#91]
Thought I'd do an issue first before a PR, incase this isn't wanted.

`undefined` is both a value and a type. Currently the highlighting for the type will follow the colouring for the value (there is no special handling for `undefined` in a type position). 

Should the type have a different colouring?

**Comment by josteink** [comment]
Good observation!

It may just be me, but I think undefined is used much more as a value (for checking incoming stuff) than as a type-declaration.

If we have to choose one (and we have to, because we cannot distinguish those 2 with our current code-base), I'd rather keep it like it is: have it highlighted as a value.

Anyone strongly opposed to this view?

**Comment by jack-williams** [comment]
> It may just be me, but I think undefined is used much more as a value (for checking incoming stuff) than as a type-declaration.

I think there is some code where it could be roughly a one-to-one correspondence, but in general, I agree with your assumption.

> If we have to choose one (and we have to, because we cannot distinguish those 2 with our current code-base), I'd rather keep it like it is: have it highlighted as a value.

Agreed; I think of the value defining the type, so having the value take precedence is intuitive.

I'm happy for this issue to be closed, unless you want to leave it open for further discussion.

**Comment by josteink** [comment]
Unless you see value in keeping it open for discussion, feel free to close at will. 👍
